# -*- coding: utf-8 -*-
# This program fetches only top artist(listed) during years 2000-2020.
# And stores result in filtered CSV file.
# We will now only work with this limited ~2000 tracks.

"""music analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VmRaGZ9ajcgN6LAD-o6vVFMoGkYaX8m
"""

import pandas as pd

df = pd.read_csv('tracks_features.csv')
df_after_2000 = df[df['year'] >= 2000]
year_counts = df_after_2000.groupby('year').size().reset_index(name='count')
print(year_counts)
total_count = year_counts['count'].sum()

print(f"Total records after 2000: {total_count}")
print(df['artists'].dtype)

df_filtered = df[df['year'].isin([2020])]
# Group by artist and count them in descending order
artist_counts = df_filtered.groupby('artists').size().reset_index(name='count')
artist_counts = artist_counts.sort_values(by='count', ascending=False)

print(artist_counts)

# Target artists
top_artists = [
    'Bruno Mars', 'Justin Timberlake', 'Ed Sheeran', 'Drake', 'Usher',
    'Adele', 'Taylor Swift', 'Rihanna', 'Lady Gaga', 'Alicia Keys',
    'Kanye West', 'Eminem','Nicki Minaj','Justin Bieber','The Weeknd', 'P!nk',
    'Maroon 5','Ariana Grande','Chris Brown',
    'Post Malone','John Legend','Sia','Miley Cyrus','Sam Smith','Demi Lovato']

# Filter for year > 2000
df_filtered = df[df['year'] >= 2000]

# Keep rows where any of the top_artists appear in the 'artists' column
df_filtered = df_filtered[df_filtered['artists'].apply(
    lambda x: any(artist in x for artist in top_artists))]

# Match artist for grouping
def get_main_artist(artist_str):
    for artist in top_artists:
        if artist in artist_str:
            return artist
    return None

df_filtered['main_artist'] = df_filtered['artists'].apply(get_main_artist)
artist_counts = df_filtered.groupby('main_artist').size().reset_index(name='count')
artist_counts = artist_counts.sort_values(by='count', ascending=False)
print(artist_counts)
df_filtered.to_csv('filtered_artist_data.csv', index=False)

